Traceback (most recent call last):
  File "/tmp/tmpm90pa0bc", line 60, in <module>
    with open('anagram_test_cases.txt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'anagram_test_cases.txt'